name: flutter_combustion_inc_example
description: "Demonstrates how to use the flutter_combustion_inc plugin."

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_combustion_inc:
    path: ../
  flutter_localizations:
    sdk: flutter
  very_good_analysis: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
