name: flutter_combustion_inc
description: "A Flutter plugin that enables communication between Flutter mobile applications and Combustion Inc. wireless temperature probes."
version: 0.0.1
homepage: https://github.com/Toglefritz/flutter_combustion_inc

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  plugin_platform_interface: ^2.0.2
  very_good_analysis: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.splendidendeavors.fluttercombustioninc.flutter_combustion_inc
        pluginClass: FlutterCombustionIncPlugin
      ios:
        pluginClass: FlutterCombustionIncPlugin
      macos:
        pluginClass: FlutterCombustionIncPlugin

  assets:
    - assets/